---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/data/home.json
  label: Home
- type: document
  path: content/data/info.json
  label: About
- type: document
  path: content/data/license.json
  label: License
- type: document
  path: content/data/privacy.json
  label: Privacy
- type: document
  path: content/data/links.json
  label: Social Links
- type: heading
  label: Content
- type: directory
  path: content/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: document
  path: content/data/authors.yaml
  label: Author List
- type: heading
  label: General Config
- type: document
  path: config.json
  label: Site Info
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: yarn dev
